version: "3"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: Schwartmanns
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - mynetwork
  webapi:
    build:
      context: ./WebApi
      dockerfile: Dockerfile
    ports:
      - "2023:80"
    volumes:
      - ./WebApi:/app
    depends_on:
      - postgres
    environment:
      - SECRET_KEY=this is my custom Secret key for authentication
    networks:
      - mynetwork
  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./website:/app
    networks:
      - mynetwork

volumes:
  db-data:

networks:
  mynetwork:
