version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - "2024:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Schwartmanns
    volumes:
      - db-data:/var/lib/postgresql/data
  webapi:
    container_name: webapi
    build:
      context: ./WebApi
      dockerfile: Dockerfile
    ports:
      - "2023:80"
    depends_on:
      - postgres
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=Schwartmanns;Username=postgres;Password=root"
      SECRET_KEY: "this is my custom Secret key for authentication"
  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./website:/app
    environment:
      VITE_API_URL: "http://localhost:2023"

volumes:
  db-data:
