FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /source

COPY *.sln .
COPY WebApi/*.csproj ./WebApi/
COPY Domain/*.csproj ./Domain/
COPY Infrastructure/*.csproj ./Infrastructure/
COPY Application/*.csproj ./Application/

RUN dotnet restore

COPY WebApi/. ./WebApi/
COPY Application/. ./Application/
COPY Domain/. ./Domain/
COPY Infrastructure/. ./Infrastructure/

WORKDIR /source/WebApi
RUN dotnet publish -c release -o /app --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
WORKDIR /app
ENV SECRET_KEY="this is my custom Secret key for authentication"
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "WebApi.dll"]